### PR TITLE
Fixed: setting schedule not working

### PR DESCRIPTION
**Pull request by horsitis**

### CODE REVIEW

**Comment by rytilahti** [comment]
Thanks for the patch, sorry for not responding earlier. Are you sure this is correct? I'll try to find to do some testing and merge it (and make a new release) this weekend.

**Comment by horsitis** [comment]
@rytilahti Yes, I am sure it is correct. I'm using this fix all the time for setting schedules.

**Comment by rytilahti** [comment]
0.1.7 with your fix is now released, thanks!

**Comment by horsitis** [comment]
Just upgraded and performed quick testing. Everything looks good.

**Pull request merged**
